navigation:
 - text: Home
   category: home
   url: /
 - text: About us
   category: about
   url: /about
 - text: Code of Conduct
   category: conduct
   url: /conduct
 - text: Contact us
   category: contact
   url: /contact
 - text: MUCK Help
   category: muck-help
   url: /muck-help
 - text: Twitter
   category: external
   url: https://twitter.com/PostfurryWorlds
